# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_thumbnail',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
